In [1]:
#Nama : Hurin Salimah
#NIM : 1103200021

# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.8995, 0.8827, 0.5145, 0.8651, 0.5443, 0.7721, 0.9787],
         [0.9351, 0.0749, 0.8490, 0.5835, 0.4602, 0.4099, 0.8256],
         [0.5250, 0.6182, 0.3518, 0.4554, 0.3386, 0.2471, 0.1130],
         [0.1395, 0.2869, 0.5954, 0.3157, 0.2483, 0.6229, 0.5268],
         [0.9709, 0.9805, 0.1034, 0.8120, 0.1786, 0.0402, 0.7267],
         [0.1530, 0.4426, 0.7974, 0.8469, 0.3046, 0.8965, 0.8701],
         [0.1740, 0.9232, 0.6349, 0.8756, 0.1303, 0.6409, 0.1659]]),
 torch.Size([7, 7]))

In [2]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[2.4903],
         [2.2991],
         [1.2449],
         [1.2928],
         [1.6896],
         [1.9207],
         [1.4432]]),
 torch.Size([7, 1]))

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [6]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [7]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617), tensor(0.3647))

In [8]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
